spring:
  data:
    mongodb:
      uri: mongodb+srv://Aman:Root@mycluster.n2lch.mongodb.net/journalApp?retryWrites=true&w=majority&appName=MyCluster
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal